### ISSUE TITLE
add tests for current JSON parsers

### ISSUE THREAD

**Issue by seanbreckenridge** [seanbreckenridge/google_takeout_parser#19]
- [ ] activity
- [ ] youtube likes
- [ ] app installs
- [ ] location history with timestampMS
- [ ] location history with isoformat time
- [ ] chrome history

**Comment by karlicoss** [comment]
for location history, [this test](thttps://github.com/karlicoss/HPI/blob/master/tests/takeout.py) should be running for HPI ci, using some public data in other github repository
