### ISSUE TITLE
Do something about http:// youtube links

### ISSUE THREAD

**Issue by karlicoss** [seanbreckenridge/google_takeout_parser#31]
It might make sense to replace `http://` with `https://` for some links, e.g. to youtube videos. 

For instance, in `Takeout/My Activity/Video Search/MyActivity.{json,html}` might contain http:// links for some old entries

```
{'header': 'youtube.com', 'title': 'Watched Octobass @ the Musical Instrument Museum - YouTube', 'titleUrl': 'http://www.youtube.com/watch?v=FP1QqtGe8ts', 'time': '2015-06-10T12:24:03.796Z', 'products': ['Video Search']}
```

In case of youtube, switching to `https` doesn't really hurt (the http/https are equivalent and both are availabe), and it might make it easier to consume downstream, e.g. might prevent duplicates.

zulip discussion: https://memex.zulipchat.com/#narrow/stream/279601-hpi/topic/google_takeout_parser/near/279605540

**Comment by seanbreckenridge** [comment]
Hmm, I guess this should be configurable, right...

Though it does look like all the http URLs (at least in `titleUrl`) are google ones:

```

In [3]: for y in res:
   ...:     if x.titleUrl and x.titleUrl.startswith("http://"):
   ...:         up = urllib.parse.urlsplit(x.titleUrl)
   ...:         x.append(up.netloc)


Counter({'maps.google.com': 1225,
         'www.google.com': 1098,
         'm.youtube.com': 18,
         'productforums.google.com': 17,
         'www.youtube.com': 15,
         'scholar.google.com': 2,
         'books.google.com': 2,
         'bp0.blogger.com': 1,
         'google.com': 1,
         'www.google.co.uk': 1})
```

Similar results with the internal `url` and `sourceUrl` from `locationInfo`

```
In [8]: Counter(items)
Out[8]: Counter({'www.google.com': 74459, b'': 33304, 'support.google.com': 33245})
```

dont want just all URLs to be converted (perhaps some websites in your history actually use http....), maybe just the common ones found in exports with a flag to configure this
