### ISSUE TITLE
support Windows separators in path_dispatch

### ISSUE THREAD

**Issue by karlicoss** [seanbreckenridge/google_takeout_parser#32]
While setting up Windows CI for promnesia, the takeout tests failed and had these in logs:
```
2022-05-09T21:03:56.5877916Z [INFO    2022-05-09 20:58:14 promnesia extract.py:49] extracting via promnesia.sources.takeout:index ...
[33m[W 220509 20:58:14 path_dispatch:270][39m No function to handle parsing My Activity\Chrome\MyActivity.html
[33m[W 220509 20:58:14 path_dispatch:270][39m No function to handle parsing My Activity\Chrome\README
```
I guess it's because in [path_dispatch](https://github.com/seanbreckenridge/google_takeout_parser/blob/master/google_takeout_parser/path_dispatch.py#L94) forward slashes are hardcoded. Perhaps the quickest fix would be to do something like `.replace(os.sep, '/')` here -- paths in takeout shouldn't have either forward or backwards slashes anyway https://github.com/seanbreckenridge/google_takeout_parser/blob/master/google_takeout_parser/path_dispatch.py#L94

**Comment by seanbreckenridge** [comment]
Ah right - must've made a mistake not removing the `\` escaping from the path strings after converting them to regex strings.

I think would make sense to leave the maps intact (other than fixing the backslash issues), and then modify the string in the [`_match_handler`](https://github.com/seanbreckenridge/google_takeout_parser/blob/692713a62abffde2e32265d28ea21057079b7c53/google_takeout_parser/path_dispatch.py?rgh-link-date=2022-05-09T21%3A29%3A59Z#L226-L227) function? Think that would be easier to read

**Comment by karlicoss** [comment]
Yep, agree, easier to keep maps as simple strings (hence the suggestion to just hack during the regex matching)!

Ah yeah -- could be the other way around depending on whether we want to patch the regex or the path. Path felt easier since means less modifications for regex (who knows how it could get in the way of escaping :) ), but don't mind either way

**Comment by karlicoss** [comment]
yeah, the promnesia config it's the most up to date  one
https://github.com/karlicoss/promnesia/blob/master/.github/workflows/main.yml

**Comment by seanbreckenridge** [comment]
should be resolved @karlicoss , let me know if the CI is still failing

**Comment by karlicoss** [comment]
thanks, the takeout tests are working now! 👍
