### ISSUE TITLE
split cached databases by type

### ISSUE THREAD

**Issue by seanbreckenridge** [seanbreckenridge/google_takeout_parser#5]
I believe this would make the size smaller since individual rows for the cachew union type would be smaller, so the cache doesnt grow to unreasonable sizes.

Would probably leave the one in [HPI google_takeout](https://github.com/seanbreckenridge/HPI/blob/master/my/google_takeout.py) as its theres just one of those, and not multiple that grow exponentially with no. of exports

As it stands, Im comfortable with the tradeoff here -- trading ease for disk space, but definitely could be improved

**Comment by karlicoss** [comment]
Another option might be keeping them in separate tables (although might make it trickier with respect to concurrency)

**Comment by seanbreckenridge** [comment]
I think I have a strategy thought out for subclassing some base dataclass which defines the cachew stuff and all the models just inherit from that

just need to write it out
